"""added onyomi_katakana, onyomi_romaji, kunyomi_hiragana, kunyomi_romaji to kanji class

Revision ID: 66005120b8c1
Revises: 2d3ba5b12872
Create Date: 2026-07-07 20:53:04.897395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66005120b8c1'
down_revision: Union[str, Sequence[str], None] = '2d3ba5b12872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('onyomi_romaji', sa.String(), nullable=True))
    op.add_column('kanji', sa.Column('onyomi_katakana', sa.String(), nullable=True))
    op.add_column('kanji', sa.Column('kunyomi_romaji', sa.String(), nullable=True))
    op.add_column('kanji', sa.Column('kunyomi_hiragana', sa.String(), nullable=True))
    op.drop_column('kanji', 'onyomi')
    op.drop_column('kanji', 'kunyomi')
    op.drop_index(op.f('ix_Users_email'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.create_index(op.f('ix_Users_email'), 'user_profiles', ['email'], unique=True)
    op.add_column('kanji', sa.Column('kunyomi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kanji', sa.Column('onyomi', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('kanji', 'kunyomi_hiragana')
    op.drop_column('kanji', 'kunyomi_romaji')
    op.drop_column('kanji', 'onyomi_katakana')
    op.drop_column('kanji', 'onyomi_romaji')
    # ### end Alembic commands ###