"""optional fields for Kanji model

Revision ID: 69b51124561e
Revises: e16104f98d54
Create Date: 2026-08-26 19:09:16.029756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b51124561e'
down_revision: Union[str, Sequence[str], None] = 'e16104f98d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kanji', 'onyomi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kanji', 'kunyomi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kanji', 'radical',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kanji', 'radical',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kanji', 'kunyomi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kanji', 'onyomi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###