"""initial tables

Revision ID: b11755d38a7c
Revises: 
Create Date: 2026-06-22 21:19:57.584762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11755d38a7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Kanji',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('onyomi', sa.String(), nullable=False),
    sa.Column('kunyomi', sa.String(), nullable=True),
    sa.Column('radicals', sa.String(), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=False),
    sa.Column('jlpt_level', sa.Integer(), nullable=False),
    sa.Column('curriculumn_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_table('ReviewLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kanji_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('response_time_s', sa.Integer(), nullable=False),
    sa.Column('ease_factor_before', sa.Float(), nullable=False),
    sa.Column('interval_before', sa.Float(), nullable=False),
    sa.Column('interval_after', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['kanji_id'], ['Kanji.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserKanji',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kanji_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kanji_id'], ['Kanji.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserKanji')
    op.drop_table('ReviewLog')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Kanji')
    # ### end Alembic commands ###
