"""last_review, next_review made optional, default for created_at

Revision ID: e16104f98d54
Revises: ff6343735cc4
Create Date: 2026-08-26 17:40:48.570010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e16104f98d54'
down_revision: Union[str, Sequence[str], None] = 'ff6343735cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kanji', 'onyomi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kanji', 'kunyomi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kanji', 'radical',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('kanji', 'stroke_count')
    op.alter_column('user_kanji', 'last_reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_kanji', 'next_review_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_kanji', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_kanji', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_kanji', 'next_review_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user_kanji', 'last_reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('kanji', sa.Column('stroke_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('kanji', 'radical',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kanji', 'kunyomi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kanji', 'onyomi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###