"""Reduced onyomi_katakana, onyomi_romaji to onyomi and katakana_hiragana, katakana_romaji to kunyomi, added None as a valid type to both if kanji has no valid entry

Revision ID: ff6343735cc4
Revises: 66005120b8c1
Create Date: 2026-07-08 18:04:02.808810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6343735cc4'
down_revision: Union[str, Sequence[str], None] = '66005120b8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('onyomi', sa.String(), nullable=True))
    op.add_column('kanji', sa.Column('kunyomi', sa.String(), nullable=True))
    op.add_column('kanji', sa.Column('radical', sa.String(), nullable=True))
    op.alter_column('kanji', 'curriculumn_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('kanji', 'kunyomi_hiragana')
    op.drop_column('kanji', 'radicals')
    op.drop_column('kanji', 'onyomi_katakana')
    op.drop_column('kanji', 'onyomi_romaji')
    op.drop_column('kanji', 'kunyomi_romaji')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('kunyomi_romaji', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kanji', sa.Column('onyomi_romaji', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kanji', sa.Column('onyomi_katakana', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kanji', sa.Column('radicals', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kanji', sa.Column('kunyomi_hiragana', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('kanji', 'curriculumn_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('kanji', 'radical')
    op.drop_column('kanji', 'kunyomi')
    op.drop_column('kanji', 'onyomi')
    # ### end Alembic commands ###